### ISSUE TITLE
Support for faceID ReID 

### ISSUE THREAD

**Issue by kzjeef** [tencent-youtu-visionseed/yt-visionseed-sdk-linux#1]
Could you support FaceID or Face Feature to support human face ReID function ?

**Comment by liangchen-harold** [comment]
We'll add FaceID support at the end of this month, but there is no plan to support ReID in the near future. Could you tell me why you need ReID?

**Comment by kzjeef** [comment]
FaceID is what I want , ReID function can be supported on host cpu. Thanks.
